# **Random Forest Regressor**

---

<br>

## What is Random Forest Regressor?
- A supervised machine learning algorithm for **regression** tasks.
- Combines multiple **decision trees** to make more accurate predictions `(an ensemble method)`.

<br>

---

<br>

## How it Works:
1. **Creates Multiple Trees**:
   - Trains on random subsets of data (bagging) and features.
2. **Averaging**:
   - Predictions from all trees are averaged to get the final result.

<br>

---

<br>

## Advantages:
- **Accurate**: Handles complex datasets well and reduces overfitting.
- **Robust**: Works well with noisy data and outliers.
- **Feature Importance**: Identifies the most important input features.

<br>

## Disadvantages:
- **Slow**: Can be computationally expensive for large datasets.
- **Less Interpretable**: Difficult to understand compared to a single tree.

<br>

---

<br>

## Use Cases:
- **Price Prediction** (e.g., housing, stock prices)
- **Weather Forecasting**
- **Energy Consumption Estimation**

<br>

---

<br>

## Overview:
Random Forest Regressor is a robust, accurate algorithm that uses multiple decision trees and averaging to make precise continuous predictions.

<br>

---

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [2]:
data = pd.read_csv('/content/51_Housing.csv')
data

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished
...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,1820000,3000,2,1,1,yes,no,yes,no,no,2,no,unfurnished
541,1767150,2400,3,1,1,no,no,no,no,no,0,no,semi-furnished
542,1750000,3620,2,1,1,yes,no,no,no,no,0,no,unfurnished
543,1750000,2910,3,1,1,no,no,no,no,no,0,no,furnished
544,1750000,3850,3,1,2,yes,no,no,no,no,0,no,unfurnished

In [3]:
data.describe()

,price,area,bedrooms,bathrooms,stories,parking
count,5.450000e+02,545.000000,545.000000,545.000000,545.000000,545.000000
mean,4.766729e+06,5150.541284,2.965138,1.286239,1.805505,0.693578
std,1.870440e+06,2170.141023,0.738064,0.502470,0.867492,0.861586
min,1.750000e+06,1650.000000,1.000000,1.000000,1.000000,0.000000
25%,3.430000e+06,3600.000000,2.000000,1.000000,1.000000,0.000000
50%,4.340000e+06,4600.000000,3.000000,1.000000,2.000000,0.000000
75%,5.740000e+06,6360.000000,3.000000,2.000000,2.000000,1.000000
max,1.330000e+07,16200.000000,6.000000,4.000000,4.000000,3.000000

In [4]:
data.isnull().sum()  # Find out Null Values - If it is 0 then No null values

price               0
area                0
bedrooms            0
bathrooms           0
stories             0
mainroad            0
guestroom           0
basement            0
hotwaterheating     0
airconditioning     0
parking             0
prefarea            0
furnishingstatus    0
dtype: int64

In [5]:
data.dropna(inplace=True)   # To drop null values from the table

In [6]:
data.columns

Index(['price', 'area', 'bedrooms', 'bathrooms', 'stories', 'mainroad',
       'guestroom', 'basement', 'hotwaterheating', 'airconditioning',
       'parking', 'prefarea', 'furnishingstatus'],
      dtype='object')

In [7]:
data = pd.get_dummies(data,columns = ['mainroad', 'guestroom', 'basement', 'hotwaterheating', 'airconditioning',
       'parking', 'prefarea', 'furnishingstatus'], drop_first=True, dtype = 'int')

In [8]:
data

,price,area,bedrooms,bathrooms,stories,mainroad_yes,guestroom_yes,basement_yes,hotwaterheating_yes,airconditioning_yes,parking_1,parking_2,parking_3,prefarea_yes,furnishingstatus_semi-furnished,furnishingstatus_unfurnished
0,13300000,7420,4,2,3,1,0,0,0,1,0,1,0,1,0,0
1,12250000,8960,4,4,4,1,0,0,0,1,0,0,1,0,0,0
2,12250000,9960,3,2,2,1,0,1,0,0,0,1,0,1,1,0
3,12215000,7500,4,2,2,1,0,1,0,1,0,0,1,1,0,0
4,11410000,7420,4,1,2,1,1,1,0,1,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,1820000,3000,2,1,1,1,0,1,0,0,0,1,0,0,0,1
541,1767150,2400,3,1,1,0,0,0,0,0,0,0,0,0,1,0
542,1750000,3620,2,1,1,1,0,0,0,0,0,0,0,0,0,1
543,1750000,2910,3,1,1,0,0,0,0,0,0,0,0,0,0,0
544,1750000,3850,3,1,2,1,0,0,0,0,0,0,0,0,0,1

In [9]:
X = data.drop(columns = 'price')
y = data['price']

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2, random_state = 29)

In [11]:
# Initialize the Random Forest Regressor

from sklearn.ensemble import RandomForestRegressor
rf_regressor = RandomForestRegressor(n_estimators=100, random_state=42)

In [12]:
# Train the regressor
rf_regressor.fit(X_train, y_train)

RandomForestRegressor(random_state=42)

In [13]:
# Predict on the test set
y_pred = rf_regressor.predict(X_test)

In [14]:
mse = mean_squared_error(y_test, y_pred)
print(mse)

1036898136914.407

In [15]:
r2 = r2_score(y_test, y_pred)
print(r2)

0.6889456577174544

In [16]:
mae = mean_absolute_error(y_test, y_pred)
print(mae)

761874.7639143729